== Protection Profile for Session Border Controlers

[cols="1,1,1,1,1,1,1,1"]
|===
8+|sbc 
| https://github.com/commoncriteria/sbc/tree/master[master] 
a| https://commoncriteria.github.io/sbc/master/sbc-release.html[📄]
a|[link=https://github.com/commoncriteria/sbc/blob/gh-pages/master/ValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/sbc/gh-pages/master/validation.svg[Validation]
a|[link=https://github.com/commoncriteria/sbc/blob/gh-pages/master/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/sbc/gh-pages/master/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/sbc/blob/gh-pages/master/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/sbc/gh-pages/master/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/sbc/blob/gh-pages/master/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/sbc/gh-pages/master/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/sbc/gh-pages/master/transforms.svg[transforms,150]
a| 
https://commoncriteria.github.io/sbc/master/diff-v1.0.html[diff-v1.0.html] +
https://commoncriteria.github.io/sbc/master/sbc-release-linkable.html[sbc-release-linkable.html] +
https://commoncriteria.github.io/sbc/master/sbc-release.html[sbc-release.html] +
https://commoncriteria.github.io/sbc/master/sbc-sd.html[sbc-sd.html] +
https://commoncriteria.github.io/sbc/master/sbc.html[sbc.html] +
|===


https://github.com/commoncriteria/sbc/issues[image:https://img.shields.io/github/issues/commoncriteria/sbc.svg?maxAge=2592000[GitHub
issues Open]]
image:https://img.shields.io/badge/license-Unlicensed-blue.svg[license]

This repository hosts the draft version of the Protection Profile for
SBC based on the This repository is used to facilitate collaboration and
development on the draft document. See the
link:#Release-Version[release] section if you are looking for the
officially released version for evaluations. A list of products that
have passed evaluation against this Protection Profile can be found
link:QQQQ[here].

=== Draft Version

* https://commoncriteria.github.io/pp/sbc/sbc-release.html[PP-Module for
SBC] (html)
* https://commoncriteria.github.io/pp/sbc/sbc-release.pdf[PP-Module for
SBC] (pdf)
* https://commoncriteria.github.io/sbc[Quick Build Directory]

=== Release Version

* https://www.niap-ccevs.org/Profile/Info.cfm?PPID=478&id=478[PP-Module
for SBC]

=== Contributing

If you are interested in contributing directly to future versions the
this Protection Profile, please consider joining the NIAP technical
community. *
https://www.niap-ccevs.org/NIAP_Evolution/tech_communities.cfm[How to
join the NIAP Technical Community (Mailing list and updates)]

=== Feedback

Questions, comments, and fixes can be submitted to the
https://github.com/commoncriteria/sbc/issues[repository issue tracker]

=== Quickstart

To clone this project along with its _transforms_ submodule run:

....
  git clone --recursive git@github.com:commoncriteria/qqqq.git
....

To pull updates from the upstream _transforms_ submodule and commit them
run:

....
 git submodule update --remote transforms
 git add transforms
 git commit
....

==== Development Info

https://github.com/commoncriteria/transforms/wiki/Working-with-Transforms-as-a-Submodule[Help
working with Transforms Submodule]

=== Repository Content

* input - Contains the `meat' of the project. It’s the input content (in
XML form) that gets transformed to readable html.
* output - The output directory where the html is placed after
transformation.
* output/images - The directory where images are stored
* transforms - Points to the transform subproject which is really a
repository for resources shared amongst many Common Criteria projects.
You shouldn’t need to modify it.

=== Links

* https://www.niap-ccevs.org/[National Information Assurance Partnership
(NIAP)]
* https://www.commoncriteriaportal.org/[Common Criteria Portal]

=== License

See link:./LICENSE[License]
